# Generated by Django 4.0.2 on 2022-02-23 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_user_usermodel_name_and_more'),
        ('quiz', '0002_remove_quizmodel_no_of_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayQuiz',
            new_name='AnswerQuiz',
        ),
    ]
