# Generated by Django 4.0.2 on 2022-02-23 04:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_user_usermodel_name_and_more'),
        ('quiz', '0003_rename_playquiz_answerquiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerQuizModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_quiz_answer', to='app.answermodel')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answering_quiz', to='app.usermodel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_quiz_question', to='app.questionmodel')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answering_quiz', to='quiz.quizmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_score', to='quiz.quizmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to='app.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='playquizmodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playquizmodel',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='AnswerQuiz',
        ),
        migrations.DeleteModel(
            name='PlayQuizModel',
        ),
    ]
