# Generated by Django 4.0.2 on 2022-02-22 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='img',
            field=models.ImageField(default='', upload_to='ans'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='img',
            field=models.ImageField(default='', upload_to='cat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_question', to='app.questionmodel'),
        ),
    ]
