# Generated by Django 4.0.2 on 2022-02-22 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_answermodel_img_categorymodel_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_category', to='app.categorymodel'),
        ),
    ]
